### ISSUE TITLE
Finish Spice Road game

### ISSUE THREAD

**Issue by Zomis** [Zomis/Games#123]
Spice Road is almost finished but a few things are remaining:

- [x] Actions needs to be serialized (call .serializer on the `factory.action` lines)
- [x] Discarding spices when you have more than 10
- [x] Gold and silver coins
- [x] Frontend view
- [x] Frontend actions
- [x] Test the game

**Comment by Zomis** [comment]
There is a bug in the game ending condition at the moment that makes the game (almost) never end.

**Comment by GustaMagik** [comment]
Bug solved

**Comment by Zomis** [comment]
Spice Road is now implemented and it works. Could look better and could use an action log, but I consider this issue solved. When bugs are found, we'll create new issues.
