### ISSUE TITLE
Avalon: Not showing all evil

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Games#145]
![avalon-bug](https://user-images.githubusercontent.com/8546320/92966443-d892b400-f477-11ea-809f-285ef394f031.PNG)

**Comment by Zomis** [comment]
Bug found:

`it.knownThumbs = it.character!!.seesThumbs().mapNotNull { ch -> game.players.find { pl -> pl.character == ch } }.toSet()`

`it.character!!.seesThumbs()` returns a Set of characters who's thumbs you are supposed to see, and this is then mapped to a player that matches this character. It's a 1-1 mapping and not 1-many mapping which is the problem.
