### ISSUE TITLE
Make it possible to report game bugs from the site

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Games#146]
A button included on all game pages (bottom/top of page perhaps), that when pressed submits a bug report.

Info it should capture:

- [ ] Game-id 
- [ ] Game info (turn / state?)
- [ ] **Optional** User input on bug. Maybe a multiple choice s.t. the user can categorize what they feel is wrong. Or free text (please no free text ^^ ).

**Comment by Zomis** [comment]
Cancelling this issue because I don't think it's worth the effort. There should instead be better tools to make sure that games are free from bugs.
