### ISSUE TITLE
authCookie expands with prefix "cookie:" on page reload

### ISSUE THREAD

**Issue by robinlarsson** [Zomis/Games#183]
1. login as guest.
2. Check authCookie = <token>
3. Reload the page.
4. Check prefixed authCookie = cookie:`<token>`
5. Reload the page.
6. Check prefixed-prefixed authCookie = cookie:cookie:`<token>`.

**Comment by Zomis** [comment]
I made some attempts fix the issue but the issue still remains it seems. Will keep working on it.

**Comment by Zomis** [comment]
Is this still an issue now? I'm not able to reproduce it right now

**Comment by robinlarsson** [comment]
I can't reproduce the issue either 🥇
