### ISSUE TITLE
AWS - Run as AWS Lambda

### ISSUE THREAD

**Issue by Zomis** [Zomis/Games#252]
Make a simple small runtime running on AWS Lambda.

Could potentially go for NodeJS because that is likely faster than running a JVM as a lambda. The game logic is written in Kotlin and can also run on JavaScript.

**Comment by vrajesh99** [comment]
yes it is easy you can create first of all lambda then connect it with the API gateway
use that api in your code.

**Comment by Zomis** [comment]
@vrajesh99 Do you have any experience of running a Lambda using a API Gateway **Websocket API** on AWS? If so, in what language? Do you have any examples to share?
