### ISSUE TITLE
AWS - Authentication

### ISSUE THREAD

**Issue by Zomis** [Zomis/Games#256]
Save the player information (playerId, name, picture) together with the websocket string identifier.

**Comment by robinlarsson** [comment]
I'm very new to this. Here are my first thoughts on how to proceed, but with lots of question marks :)

* add my own AWS url to serverOptions.
* set server via url query: http://localhost:8080/#/login?server=aws2
* in AWS, create a new table "players"?
** playerId - auto generated by the backend?
** name - does the frontend send this today? Or do we need to extend the body?
** picture - does the frontend send this today? Or do we need to extend the body?
** websocket id - is this saved in the requestContext? connectionId?
* in AWS, update the route "auth" to store the data - https://github.com/Zomis/Games-nodejs/blob/main/src/routes/auth.js

**Comment by Zomis** [comment]
Add AWS url to serverOptions and set server via URL query: Yes indeed.

Update the route "auth" to store the data: Yes indeed.

But with regards to the table, the goal is that *the entire application* should only be using **one** table. This can be done using a system like https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html . This system is already in use today. It can be a bit confusing in the beginning, but it is very powerful.

I will give some examples of how it is currently used:

In the table, there is the entry with PK `player:b4c6bb4b-3430-4384-9670-3b6e80f7ee17` and SK `oauth:github/Zomis`, Data `1625587202` and PlayerName `Zomis`.

Thanks to the Global Secondary Index of the table which indexes on Sort Key SK and Data (numeric value), when I login using GitHub DynamoDB can look for `oauth:github/Zomis` and Data > 0. If such an item exists, use it to get the playerId. If it does not exist, generate a new playerId (UUID) and save an entry to the database.

---

Game data is saved in a similar way.

PK: `game:c93d012b-8459-4865-90d6-1ed8b46389a4` and SK with the same value contains information such as: GameType, timestamp of when game was started, and a few other things.

There is also an entry with the same Partition Key (PK) but with the SK `player:3064b303-39ca-4526-ac2c-2323f8e96dac` containing information about that specific player, such as which playerIndex that player is playing as.

Similarly, the same PK also has SK `zmove:0` which contains data about the first move that was made. In this case, `PlayerIndex = 0`, `MoveType = play`, `Move = { "x" : 5, "y": 3 }` which contains all the information about the first move in a game.

The prefix `z` in `zmove` makes it possible to get all the information for the game *except* the move information, by querying on PK `game:c93d012b-8459-4865-90d6-1ed8b46389a4` and SK `between 'a' and 'y'`

---

So a possible way to save this in DynamoDB would be:

PK `ws:<connectionId>`, SK the same.

And then also save `PlayerId`, `Name` and `Picture` from below:
- PlayerId - auto generated by the backend the first time the user logs in, for recurring users this is fetched from DynamoDB.
- Name - Is fetched by backend in a call to the corresponding authentication service (Google / GitHub), for guests it is generated from a list of adjectives and a list of animal names and a number from 10 to 99.
- Picture - Is fetched by backend in a call to the corresponding authentication service (Google / GitHub), for guests it is generated based on a MD5 checksum of the playerid or similar and is then using the Gravatar service to get a generated picture
- WebsocketId - is the same as the `connectionId` available in the `requestContext` (needs only to be saved in the PK)

Relevant code in the existing server is:
- https://github.com/Zomis/Games/blob/main/games-server/src/main/kotlin/net/zomis/games/server2/javalin/auth/LinAuth.kt
- https://github.com/Zomis/Games/blob/main/games-server/src/main/kotlin/net/zomis/games/server2/AuthorizationSystem.kt

**Comment by Zomis** [comment]
Here's how to get an instance of AWS DynamoDB:

```
const AWS = require('aws-sdk'); 
const ddb = new AWS.DynamoDB.DocumentClient({ apiVersion: '2012-08-10', region: "eu-north-1" });
```

**Comment by Zomis** [comment]
Implemented in separate repository
