### ISSUE TITLE
On player turn, indicate with ring bell sound

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Games#49]

**Comment by Zomis** [comment]
Sounds have not yet been implemented at all, but I'm using it in another Vue project so it can be added.

If added, an option to turn off sounds would be necessary.

Suggestion for specific sound file to play welcome.

**Comment by GustaMagik** [comment]
https://freesound.org/people/InspectorJ/sounds/415510/

**Comment by GustaMagik** [comment]
or https://freesound.org/people/FoolBoyMedia/sounds/234524/

**Comment by GustaMagik** [comment]
Think this would be good server-wide (all games could use a notification sound)

**Comment by Zomis** [comment]
See and evaluate https://github.com/Zomis/Games/pull/174

**Comment by Zomis** [comment]
@GustaMagik Please comment what you think about the sound effect. Some sound has been added at least. Closing until any sound-changes are needed.

**Comment by Zomis** [comment]
Personally I think this sound might be a bit annoying as it has a very long after-sound: https://freesound.org/people/InspectorJ/sounds/415510/

But the other suggested sound might be good. Compare that with the current implemented sound.
