### ISSUE TITLE
Remove user icons on top

### ISSUE THREAD

**Issue by Motsols** [Zomis/Games#51]
It's only icons and no names etc, so they can be removed to save space

**Comment by Zomis** [comment]
The plan is to also show the names of people playing there. This is a common component that is shared among all the games. It's sort of a game header to indicate the game name (Hanabi in this case), the people playing (picture + name) and possibly - for some games - their score.

**Comment by Etrisa** [comment]
Make names go in rows of X, at the moment they just go in a line top to bottom.
Also align columns better so it looks nicer.

**Comment by Etrisa** [comment]
Example of coloumns:
![image](https://user-images.githubusercontent.com/10958425/81404941-f7cead00-9136-11ea-978d-b754c71eb14a.png)

But really make them go in a line and break when there's to many players to have a nice line.

**Comment by Zomis** [comment]
I should add that at the moment how this component looks depends on how many players are in the game.

Please try to think about solutions that can be applicable to many situations, depending on the game being played and the number of players etc.

**Comment by Zomis** [comment]
I have realized that for some games this component is probably not needed at all, such as Splendor and Hanabi.

The game name could be shown in the title instead, and games where this component might be needed could use the component without forcing it on all games to show it.

**Comment by GustaMagik** [comment]
I'd rather:
1. move the game title to beside the Zomis Games link.
2. display the players in the game on one compact row (possibly only v-avatars)
  - and highlight (border with color) the active player

Why:
It is good to have a generic component in every game that shows the active player + which players are in the game.

**Comment by Zomis** [comment]
It's now up to each game whether or not to include the `GameHead` (which is the old component).

Most of the newer games have already a nice way to show all players that are in the game, I think that's enough for now.
