### ISSUE TITLE
Make it more obvious when the game has ended

### ISSUE THREAD

**Issue by Motsols** [Zomis/Games#54]
It's not clear when the game ends

**Comment by Zomis** [comment]
Suggestions for how to display it?

**Comment by Motsols** [comment]
Popup maybe? Alternatively a score screen that takes place in an obvious place are two things I can think of from the top of my head

**Comment by Zomis** [comment]
All your cards get revealed when the game is over. Maybe not super clear that the reason for them getting revealed is that the game is over, but still :)

**Comment by Zomis** [comment]
I'd also like to avoid popups, I believe that those are often not good UX. But I'd definitely want it to be clearer that the game is over somehow.

**Comment by GustaMagik** [comment]
we could show it with v-snackbar
imo popups/toasts are excellent for site notifications if you just ensure that the user does not have to act on them.

**Comment by Zomis** [comment]
I'm thinking that this could be a site-wide feature for all games?
