### ISSUE TITLE
[Guest] Possibility to swap display name

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Games#55]

**Comment by Zomis** [comment]
Yes, this is something I have considered and have planned to implement.

**Comment by Zomis** [comment]
Additionally, guests should be given a cookie that can identify them so that they have the possibility to rejoin.

**Comment by GustaMagik** [comment]
> Additionally, guests should be given a cookie that can identify them so that they have the possibility to rejoin.

But the cookie could be a separate issue?

**Comment by Zomis** [comment]
@GustaMagik Absolutely correct.

**Comment by Zomis** [comment]
Use a name generator instead of numbers, such as https://codereview.stackexchange.com/q/64402/31562 and https://www.paperrater.com/page/lists-of-adjectives.

**Comment by GustaMagik** [comment]
Aardvark
Albatross
Alligator
Alpaca
Ant
Anteater
Antelope
Ape
Armadillo
Baboon
Badger
Barracuda
Bat
Bear
Beaver
Bee
Binturong
Bird
Bison
Bluebird
Boar
Bobcat
Buffalo
Butterfly
Camel
Capybara
Caracal
Caribou
Cassowary
Cat
Caterpillar
Cattle
Chameleon
Chamois
Cheetah
Chicken
Chimpanzee
Chinchilla
Chough
Coati
Cobra
Cockroach
Cod
Cormorant
Cougar
Coyote
Crab
Crane
Cricket
Crocodile
Crow
Cuckoo
Curlew
Deer
Dhole
Dingo
Dinosaur
Dog
Dogfish
Dolphin
Donkey
Dove
Dragonfly
Duck
Dugong
Dunlin
Eagle
Echidna
Eel
Eland
Elephant
Elephant seal
Elk
Emu
Falcon
Ferret
Finch
Fish
Flamingo
Fly
Fox
Frog
Gaur
Gazelle
Gecko
Gerbil
Giant panda
Giraffe
Gnat
Gnu
Goat
Goldfinch
Goosander
Goose
Gorilla
Goshawk
Grasshopper
Grouse
Guanaco
Guinea fowl
Guinea pig
Gull
Hamster
Hare
Hawk
Hedgehog
Hermit crab
Heron
Herring
Hippopotamus
Hoatzin
Hoopoe
Hornet
Horse
Human
Hummingbird
Hyena
Ibex
Ibis
Iguana
Impala
Jackal
Jaguar
Jay
Jellyfish
Jerboa
Kangaroo
Kingfisher
Kinkajou
Koala
Komodo dragon
Kookaburra
Kouprey
Kudu
Lapwing
Lark
Lemur
Leopard
Lion
Lizard
Llama
Lobster
Locust
Loris
Louse
Lynx
Lyrebird
Macaque
Macaw
Magpie
Mallard
Mammoth
Manatee
Mandrill
Marmoset
Marmot
Meerkat
Mink
Mole
Mongoose
Monkey
Moose
Mosquito
Mouse
Myna
Narwhal
Newt
Nightingale
Nine-banded armadillo
Octopus
Okapi
Opossum
Orangutan
Oryx
Ostrich
Otter
Owl
Oyster
Panther
Parrot
Panda
Partridge
Peafowl
Penguin
Pheasant
Pig
Pigeon
Pika
Polar bear
Pony
Porcupine
Porpoise
Prairie dog
Pug
Quail
Quelea
Quetzal
Rabbit
Raccoon
Ram
Rat
Raven
Red deer
Red panda
Reindeer
Rhea
Rhinoceros
Rook
Salamander
Salmon
Sand dollar
Sandpiper
Sardine
Sea lion
Seahorse
Seal
Shark
Sheep
Shrew
Siamang
Skunk
Sloth
Snail
Snake
Spider
Squid
Squirrel
Starling
Stegosaurus
Swan
Tamarin
Tapir
Tarsier
Termite
Tiger
Toad
Toucan
Turaco
Turkey
Turtle
Umbrellabird
Vicuña
Vinegaroon
Viper
Vulture
Wallaby
Walrus
Wasp
Water buffalo
Waxwing
Weasel
Whale
Wobbegong
Wolf
Wolverine
Wombat
Woodpecker
Worm
Wren
Yak
Zebra
