### ISSUE TITLE
Action Log

### ISSUE THREAD

**Issue by Zomis** [Zomis/Games#65]
A lot of people have requested an action log in Hanabi. There's a few possible solutions to this:

- Display a small bar at the top showing what all actions are
  - guest-123 --> guest-456 White (Display white card)
  - guest-123 --> guest-456 3's (Display gray 3)
  - guest-123 --> Play White 3 (Display white 3)
  - guest-123 --> Discard White 3 (Display white 3, marked with a cross or something)
- Use a "live replay" so that you have the possibility to go back and see how the game looked like at an earlier stage, and then have the possibility to go back again (similar to Lichess)

There is however one possible problem with this: Clients may not be aware of the previous actions, only about the current state. This can probably be mitigated though, as Clients should be informed whenever someone performs an action.

**Comment by GustaMagik** [comment]
This might be a feature that all games want.
A toggleable transaction log:
Player A made move X
Player B made move Y
...

**Comment by Zomis** [comment]
With the new rule-based system in #89 it could be quite easy to implement something like this.

For example:

`action(play).log { message("$player played $card", action.playerIndex, action.card) }`

Could also be applied to Triggers:

`myTrigger.log { message("MyTrigger occurred and caused $stuff!", trigger.stuff) }`

These things could then be stored in frontend and using the variables it could also be possible to solve #43.

Hanabi example: (exact syntax to be determined

`action(play).log { "$player played $card" }` highlights `card` in frontend and adds log like "Zomis played white 3"

`action(discard).log .... (same as action(play)`

`action(giveClue).log { "$player gave clue to $targetPlayer about $affectedCards $clueValue" }` highlights `affectedCards` in frontend and adds log like "Zomis gave clue to GustaMagic about two white cards"

Needs to be stored in frontend as an object: `{ message: ..., highlight: ... }` (should it use a generic `highlight` key or a more specific `affectedCards` key? Need to make sure they are highlighted somehow.

**Comment by Zomis** [comment]
It could certainly look better, but the first version of the action log now exists on the new-actions branch.
