### ISSUE TITLE
Swap way of showing active player to be highlighted border

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Games#77]

**Comment by Zomis** [comment]
The style for active player should be common throughout the site.

**Comment by Zomis** [comment]
First step:
- Look in `Splendor.vue` or `SplendorPlayer.vue` how active player is handled there and copy to `Hanabi.vue`

Second step:
- Create a common CSS for this in one of the common CSS files and import that in the other game components.

**Comment by Zomis** [comment]
Using the border like in Splendor might not be optimal, as the size of the v-card then changes depending on if the player is active or not. An approach for how to do this in a non-size-changing way would be nice. Perhaps use some box-shadow, similar to what Hanabi uses for highlighting last action?

**Comment by Zomis** [comment]
Changing background color to something light that is not yellow might be another option

**Comment by Zomis** [comment]
These options of highlighting current player exists right now:
https://games.zomis.net/#/local/Hanabi - green text
https://games.zomis.net/#/local/Splendor - yellow border
https://games.zomis.net/#/local/LiarsDice - background color
https://games.zomis.net/#/local/Skull - border shadow

I need lots of input on which of these ways are preferable, what is good or what is bad with each approach, and how can it be improved?

**Comment by Zomis** [comment]
I think the best way would be to use both background color and border shadow.

Haven't heard much feedback about this recently, it seems like both ways that are used at the moment are good enough.

**Comment by Zomis** [comment]
Fixed in commit 826a96d554f9b1e03be94542a6973934bef70f9b
